title: Your awesome title
subtitle: Your awesome subtitle
description: >-
  This is the demo site for a Jekyll theme version of HTML5 UP's sleek,
  responsive site template Prologue.
author: Your Incredible Name
email: your-email@example.com
avatar: assets/images/avatar.jpg
baseurl: ''
url: ''
twitter_url: null
facebook_url: null
googleplus_url: null
instagram_url: null
linkedin_url: null
github_url: null
stackoverflow_url: null
pinterest_url: null
slack_url: null
dribbble_url: null
google_analytics: null
theme: jekyll-theme-prologue
collections:
  - sections
